### ISSUE TITLE
Creating the Angular Application

### ISSUE THREAD

**Issue by lakenney** [joeeames/MEANAppsFiles#15]
Main partial doesn’t seem to be working
app.js
.when('/', { templateUrl: '/partials/main', controller: 'mainCtrl'})
});
angular.module('app').controller('mainCtrl', function($scope){
$scope.myVar = "Hello Angular";
});

server.js
.when('/', { templateUrl: '/partials/main', controller: 'mainCtrl'})
});
angular.module('app').controller('mainCtrl', function($scope){
$scope.myVar = "Hello Angular";
});

When someone requests /partials/main, express should render the
main.jade inside the partials directory inside the views directory. The
server is running correctly but I don’t see “This is a Partial … Hello
Angular” 
https://github.com/lakenney/multivision/commit/9c41ca890f89bf8b310d67b193886f41109c6fa2
I reviewed the files a few times so it all looks good but I get nothing in the browser.

**Comment by joeeames** [comment]
Thanks for taking the time to post, sorry you're having trouble. In general, it's best to post these issues to the discussion forum of the course. In your case, every time one of these problems happens, it's always because of 1 of 2 things. Something not set up, or more likely, a missed step/mistyped code. Try backing up a clip or two, make sure that things are working, then go forward again. This will usually find the problem.

I'm going to close this issue, if you don't mind, if you can't solve the problem using the above advice, post in the forum for the course and we can address it there.
